name: Invitation to the GitHub Organization
description: I would like to be part of the awesome organization
title: "Please invite me to the GitHub Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you come to know about PixelExtended? What do you like about this community/Why do you want to join?
    validations:
      required: true